### ISSUE TITLE
Output does not show sink if used with wildcards

### ISSUE THREAD

**Issue by bluec0re** [googleprojectzero/weggli#14]
# Description

When using variables with wildcards instead of actual function names, the location where a variable is used is not shown.

For example `{ $b = getenv(_); _(_, $b); }` vs `{ $b = getenv(_); printf(_, $b); }`

# Expected

```c
void displayHelp()
{
  char *c = getenv("HOME");
  int t;
  endwin();
  printf("%s\n",version);
  printf("Usage: dav [arguments] [FILENAME] [FILENAME] [LNUM] ...\n");
  printf("  where FILENAMEs, if specified, are the names of the files you wish to load.\nThe + or -l arguments must be after the filename.\n");
..
  }
  printf("  Ctrl-C : Quit (won't ask for save)\n");
  printf("  Ctrl-K : Erase to end of line\n");
  printf("  Ctrl-U : Erase whole line\n");
  printf("Personal options:\n");
  printf("  Located in %s/.davrc\n",c);
  printf("  Edit %s/.davrc to customize function key bindings\n",c);
  initscr();
  quit("");
}
```

# Actual

```c
void displayHelp()
{
  char *c = getenv("HOME");
  int t;
  endwin();
  printf("%s\n",version);
  printf("Usage: dav [arguments] [FILENAME] [FILENAME] [LNUM] ...\n");
  printf("  where FILENAMEs, if specified, are the names of the files you wish to load.\nThe + or -l arguments must be after the filename.\n");
..
}
```

**Comment by felixwilhelm** [comment]
So the problem is that _(...) is actually a special syntax for sub expressions
For example, _(x) would match on x+10 or &buf[func(x)]. So _($b) and $randomvar($b) match on completely different stuff. 
Using _(..) with more than a single argument is not supported, so the $b in your example query was just silently dropped.

That's pretty bad so ee46063 tries to make this a bit more user-friendly: It warns when a user uses a sub expression wildcard with more than a single argument and it automatically converts them to a query matching on function calls instead.

The correct long-term (and breaking) change is probably to find a better syntax for sub expressions. I'm open for suggestions :)
